### ISSUE TITLE
Bar Card

### ISSUE THREAD

**Issue by sockerbagarn** [linsvensson/sensor.greenely#1]
Is it possible to use this data in mini-graph-card for example to better visualize the trend? 
Im not able to get the values in a graph.
Anyway, great work!

**Comment by linsvensson** [comment]
Sadly it is not possible :(
Thanks!

**Comment by vlumikero** [comment]
I'm also trying to get a plot of historical data, e.g. the last 7 days. I'm a noob when it comes to python and I'm trying to understand enough of it to be able to help.

As far as I can tell, the API provides all that's needed (either daily or hourly summary), but only for historical data, starting yesterday. Is the problem that the sensor value's time stamp in HA can only be populated based on the current time? I.e. that it's not possible to retrofit values? Could an aggregate function be used, perhaps like the Utility Meter combined with an offset?

**Comment by linsvensson** [comment]
@vlumikero That's exactly the problem! I'm also new at python so you're not alone. 
Hmm I haven't actually looked much at the Utility Meter, I'll have a look later this week, but it might be an idea!
If you come up with anything feel free to submit a pull request.

**Comment by tempmaseg** [comment]
Have a look at: #3, it should help you out.
