### ISSUE TITLE
Unexpected unit of measurement

### ISSUE THREAD

**Issue by Golab** [linsvensson/sensor.greenely#10]
I can’t get to work anymore

Unexpected unit of measurement

Translation Error: The intl string context variable "currency" was not provided to the string "The following entities do not have the expected units of measurement ''{currency}/kWh'' or ''{currency}/Wh'':"
sensor.greenely_usage (kWh)

running

Home Assistant OS 6.5
Update Channel | beta
Supervisor Version supervisor-2021.10.0

![95578FB5-088A-4800-946B-8EC74329719A](https://user-images.githubusercontent.com/1252745/137301901-fcb124c0-e826-46ce-93ac-4c663eaee8b0.png)

**Comment by tempmaseg** [comment]
Update sensor.greenely_usage with the following attributes and you will be able to add it:
  device_class: energy
  state_class: measurement
  last_reset: '1970-01-01T00:00:00+00:00'
  
  However, since the sensor only updates once/day with yesterdays value it looks a bit weird in the energy dashboard.

**Comment by Golab** [comment]
Hej igen tar det på svenska nu, kan du förklara hur jag lägger till det? Är ganska ny

**Comment by tempmaseg** [comment]
Absolut, säg till om något är otydligt. 

För att lägga till sensor.greenely_usage som grid consumption, behövde jag lägga till följande i customize.yaml

```
sensor.greenely_usage:
  device_class: energy
  state_class: measurement
  last_reset: '1970-01-01T00:00:00+00:00'
  ```

Se till att ha följande i configuration.yaml  för att HA ska läsa in ändringarna. 
```
homeassistant:
  customize: !include customize.yaml
```

**Comment by linsvensson** [comment]
Closing
