### ISSUE TITLE
Incorrect hour for hourly usage

### ISSUE THREAD

**Issue by tempmaseg** [linsvensson/sensor.greenely#11]
Thanks for the integration :)

I get the wrong hour for the hourly usage. The problem is most likely related to summer/winter time. 

The hourly data for 16:00 in Greenely apps shows up as 17:00 in Home Assistant.

**Comment by linsvensson** [comment]
I'm looking at this now and... I seem to be getting the right values? Could you send me a screenshot of yours?

**Comment by tempmaseg** [comment]
Sure, PFA.

As you can see in Greenely app, the 1,2kwh consumption is at 16:00 but in HA it is at 17:00. 

![usage1](https://user-images.githubusercontent.com/55505550/145947577-c6784292-71ad-4c99-a35b-a4775a810fee.png)
![usage2](https://user-images.githubusercontent.com/55505550/145947556-4cc700ce-ab21-4228-8491-c5b42df438b0.png)
![usage3](https://user-images.githubusercontent.com/55505550/145947555-bd0f5e99-5625-4565-af11-6011078b3233.jpg)

**Comment by linsvensson** [comment]
Hmm okay, I'll have a closer look tonight. It seems the app uses a different API call now, and my usage sensor only shows 0 🤔

**Comment by linsvensson** [comment]
@tempmaseg I pushed an update now, please let me know if it works :)

**Comment by tempmaseg** [comment]
Thank you, it looks correct now! :)

You can update the lovelace configuration for the apexcard in readme to use graph_span: 24h instead of graph_span: 25h :)
