### ISSUE TITLE
Implements device_state_attributes.

### ISSUE THREAD

**Issue by tempmaseg** [linsvensson/sensor.greenely#12]
Hi,

Getting the following warning message when starting up the integration, I assume it is related to some general update of sensors.

_"Entity sensor.greenely_usage (<class 'custom_components.greenely.sensor.GreenelyUsageSensor'>) implements device_state_attributes. Please report it to the custom component author."_

**Comment by linsvensson** [comment]
Will have a look!

**Comment by tempmaseg** [comment]
Last release solved the warning message! :)

Thanks!
