### ISSUE TITLE
Apexchart version 1.10.0 problem

### ISSUE THREAD

**Issue by AndersHub** [linsvensson/sensor.greenely#14]
Hi I also use Apex but I have some problem regarding Greenly and your code. I get this error "/// apexcharts-card version 1.10.0 /// value.header is not a ChartCardHeaderExternalConfig; value.header.graph_span is extraneous" .

My lovelace code is in the attached file.

Thanks in advance
[Lovelacecode.txt](https://github.com/linsvensson/sensor.greenely/files/7830781/Lovelacecode.txt)
.

**Comment by tempmaseg** [comment]
Hi Anders,

Sorry for slow reply, which apex card is giving you the error? I only need the lovelace code for that card :).

**Comment by AndersHub** [comment]
I have solved the problem.
