### ISSUE TITLE
Sensor sensor.greenely_prices missing

### ISSUE THREAD

**Issue by PatricDahl** [linsvensson/sensor.greenely#15]
Hi,

To begin with, thanks for all good work on this component.

suddenly _price sensor missing in HA, have logged into Greenly mobile app and there I still see prices.
Sensor _usage I'll still see. Could you help me to understand what´s the issue?

sensor:
  - platform: greenely
    email: xxx@gmail.com
    password: xxx
    usage: true
    prices: false
    sold: true
    show_hourly: true
    sold_daily: true
    usage_days: 4
    sold_measure: 6
    time_format: '%Y-%m-%dT%H:%M'
    date_format: '%Y-%m-%d'

2022-01-25 00:56:35 DEBUG (SyncWorker_1) [custom_components.greenely.sensor] jwt is valid!
2022-01-25 00:56:35 DEBUG (SyncWorker_1) [custom_components.greenely.sensor] Fetching usage data...
2022-01-25 00:56:36 DEBUG (SyncWorker_2) [custom_components.greenely.sensor] Checking jwt validity...
2022-01-25 00:56:36 DEBUG (SyncWorker_2) [custom_components.greenely.sensor] jwt is valid!

Thanks in advance
Patric

**Comment by rasssta** [comment]
Just installed the integration and I have the same issue. I'm using HASS 2021.12.9.

**Comment by rasssta** [comment]
Might be related to https://github.com/linsvensson/sensor.greenely/pull/13

**Comment by PatricDahl** [comment]
Yes, changing accordingly to #13 helped me.

- value = data['current_month']['value'] + value = data['current_month'][
'value'] if data['current_month'] else 0 Many thanks.


Den mån 31 jan. 2022 kl 11:59 skrev rasssta ***@***.***>:

**Comment by linsvensson** [comment]
Closing this issue as a merge solved it
