### ISSUE TITLE
Får det inte att fungera

### ISSUE THREAD

**Issue by MrGlad8** [linsvensson/sensor.greenely#16]
Hejsan! Tack för detta, är rätt ny på HA men detta är något jag gärna hade önskat ha i min HA.
Men om jag fattar det hela rätt så ska man kopiera filerna till custom_components > greenely. Dom har jag där.
Sen så ändrade jag i configuration.yaml och la till under default_config:

template:
sensor:
  - platform: greenely
    email: (min mail)
    password: (mitt lösen)
    usage: true
    prices: false
    sold: true
    show_hourly: true
    sold_daily: true
    usage_days: 4
    sold_measure: 6
    time_format: '%H'
    date_format: '%d/%m/%Y'

Och jag kan lägga till kortet i min overview men där står det bara Greenely Usage 0 kWh.

Är det något jag gör fel? :) 

Tack!

**Comment by MrGlad8** [comment]
Eller rättare sagt, jag får det att fungera men ser bara dagens totala användning. Får den inte att visa per timma!

**Comment by linsvensson** [comment]
Hej! Vilket kort testar du med? Ser värdena rätt ut i sensorn under developer tools?

**Comment by MrGlad8** [comment]
Kör jag bara direkt via Entity > Greenely Usage och tar add to Lovelace så får jag bara gårdagens förbrukning.
Testar jag via ApexChart så får jag lite problem.
Jag testar att ta bort det sista:
data_generator: |
        return entity.attributes.hourly.map((entry) => {
          return [new Date(entry.time), entry.usage];
        }); 
Och då får jag också bara gårdensförbrukning, har jag med strängen ovan så får jag konstiga värden som verkar slumpmässiga? 
Eller hur ska jag skriva det sista för att det ska bli rätt?

**Comment by MrGlad8** [comment]
Men ja under developer tools så ser värdena rätt ut, dock gårdagens värden. Men när jag kör in det i Apex Charts så verkar det bli knas.. den visar ju förbrukningen nu senaste timmen i staplar, och det ska den väl inte kunna visa?

**Comment by linsvensson** [comment]
Vill du se priser får du sätta `prices: true` istället för false :)
Hmm lite osäker på hur usage bör visas...

**Comment by MrGlad8** [comment]
Du menar i sensor.py? Där står dom som true!
Men jag kopierar hela din kod in i charten:

type: custom:apexcharts-card
header:
  title: Förbrukning/timme & elpris
  show: true
graph_span: 24h
span:
  start: day
  offset: '-1d'
yaxis:
  - id: first
    apex_config:
      tickAmount: 10
    min: 0
    max: 2
  - id: second
    opposite: true
    apex_config:
      tickAmount: 5
    min: 0
    decimals: 0
apex_config:
  dataLabels:
    enabled: false
  stroke:
    width: 4
series:
  - entity: sensor.greenely_usage
    name: Förbrukning
    yaxis_id: first
    type: column
    color: red
    extend_to_end: false
    show:
      legend_value: false
    data_generator: |
      return entity.attributes.hourly.map((entry) => {
        return [new Date(entry.time), entry.usage];
      }); 
  - entity: sensor.greenely_prices
    data_generator: |
      return entity.attributes.previous_day.map((entry) => {
        return [new Date(entry.date + 'T' + entry.time), entry.price];
      }); 
    yaxis_id: second
    type: line
    color: blue
    name: Elpris
    show:
      legend_value: false
    extend_to_end: false



Men får bara att prices: entity not avalible!

**Comment by MrGlad8** [comment]
Men vad för kod ska jag köra om jag inte vill ha priser, bara förbrukning per timme? 
Skulle du kunna skriva ner den koden?
Tack!

**Comment by MrGlad8** [comment]
Har som sagt satt prices till true, men får ändå Entity not available: sensor.greenely_prices
Vad för kod ska jag använda om jag vill se per timme utan priser?

**Comment by MrGlad8** [comment]
Priser fungerar inte tror jag, trots prices: true!
Men fick förbrukning/timme att funka. Fattade ju inte att jag var tvungen att lägga til raden "show_hourly: true" i cinfiguration.yaml. Nu fungerar det! Toppen, tack så mycket!

**Comment by raolss** [comment]
Jag får inte heller priser att funka.

**Comment by MrGlad8** [comment]
Nej samma här @raolss men funderade på det och jag tror inte jag behöver det. För vilket pris visar den? Alla har väl olika elavtal mm. Man borde kunna skriva in sitt egna pris på något sätt.

**Comment by raolss** [comment]
Förutsätter att den visar spotpriser per timme.

**Comment by raolss** [comment]
@MrGlad8 fick det att funka med koden som ligger som pull request för #13 som refereras från #15

**Comment by OscarUltrael** [comment]
> Kör jag bara direkt via Entity > Greenely Usage och tar add to Lovelace så får jag bara gårdagens förbrukning. Testar jag via ApexChart så får jag lite problem. Jag testar att ta bort det sista: data_generator: | return entity.attributes.hourly.map((entry) => { return [new Date(entry.time), entry.usage]; }); Och då får jag också bara gårdensförbrukning, har jag med strängen ovan så får jag konstiga värden som verkar slumpmässiga? Eller hur ska jag skriva det sista för att det ska bli rätt?

Hittade du någon lösning till Apexcharts? Har samma problem som dig just nu.

**Comment by linsvensson** [comment]
Sensorns attribut **hourly** visar gårdagens data.
Skulle du kunna visa bild på vad för slumpmässiga värden du får? Stämmer de inte överens med hourly i sensorn?

**Comment by linsvensson** [comment]
Stänger denna pga inaktivitet, öppna en ny issue om du fortfarande har problem :)
