### ISSUE TITLE
No houerly redings?

### ISSUE THREAD

**Issue by JohanGill69** [linsvensson/sensor.greenely#18]
Min sensor ger bara 0 värden för timmarna. Priset och 2 dagar gammal förbrukning visas i sensorerna.
Jag ser i dokumentationen att sensorn ska visa gårdagens data men jag får bara 2 dagar gammal data i sensorn. Även i Greenelys app får jag bara två dagar gammal data ( jag använder iPhone ). Går det ändra så att sensorn hämtar två dagar gammal data?

**Comment by JohanGill69** [comment]
<img width="385" alt="Skärmavbild 2022-03-06 kl  21 51 26" src="https://user-images.githubusercontent.com/47776736/156941790-2259d578-bc61-45ec-80c9-9a5b3675367c.png">

**Comment by linsvensson** [comment]
Ah okej du menar hourly usage för 2 dagar sedan?

**Comment by JohanGill69** [comment]
Ja precis, två dagar gammal data men timme för timme. Efter som Greenely släpar med data för timmarna så blir det inga värden i sensorn.

**Comment by linsvensson** [comment]
Jag testar lite och uppdaterar strax med en version där du kan sätta **hourly_offset_days** till 2 :)

**Comment by JohanGill69** [comment]
Strålande, tack

**Comment by linsvensson** [comment]
Fick du det att lira?

**Comment by JohanGill69** [comment]
Ja nu funkar det, Nu får jag timdata för en dag den 8:e (idag den 11:e).

**Comment by linsvensson** [comment]
Perfekt! Då stänger jag denna
