### ISSUE TITLE
Cannot get it to work in HA 0.112.2

### ISSUE THREAD

**Issue by csalhammar** [linsvensson/sensor.greenely#2]
Trying to add this custom component in HA 0.112.2.
Have downloaded the files and added them to: "\config\custom_components\greenely"
(_init_.py
manifest.json
sensor.py)

After restart, no error so started to add the sensor in my sensor.yaml like:
- platform: greenely
  email: *****
  password: *****
 show_usage: true
  show_daily_prices: false
  usage_days: 5
  date_format: %d/%m/%Y

When saved and checking config I get the error:
"Error loading /config/configuration.yaml: while scanning for the next token
found character '%' that cannot start any token
  in "/config/sensor.yaml", line 13, column 16"

Removed date_format line getting this error:
Invalid config for [sensor.greenely]: [show_usage] is an invalid option for [sensor.greenely]. Check: sensor.greenely->show_usage. (See ?, line ?). 

Removed all lines exept:
- platform: greenely
  email: *****
  password: *****
Gets the same error.

Any idea how to solve this?
Or am I doing something wrong?

BR
Christoffer

**Comment by linsvensson** [comment]
**show_usage** should be **usage**
**show_daily_prices** should be **prices**
I've updated the Readme fully now :)

What error did you get with the default config?

**Comment by csalhammar** [comment]
Thanks, now I get it to work as long as I don't have:
date_format: %d/%m/%Y
Getting error:
"Error loading /config/configuration.yaml: while scanning for the next token
found character '%' that cannot start any token
  in "/config/sensor.yaml", line 13, column 16"

**Comment by linsvensson** [comment]
I'll have a look!

**Comment by linsvensson** [comment]
Sorry for the long wait. 
You actually need to put it in quotes, so it should be `date_format: '%d/%m/%Y'`. 
Then it will work :)
