### ISSUE TITLE
Missing sensor

### ISSUE THREAD

**Issue by bmd322** [linsvensson/sensor.greenely#20]
Jag får ingen sensor för såld el. Eller det ska man inte kanske? Jag har detta i configuration.yaml
  - platform: greenely
    email: ***@***.***
    password: *******
    usage: true
    prices: true
    sold: true
    show_hourly: true
    sold_daily: true
    usage_days: 4
    sold_measure: 6
    time_format: '%Y-%m-%dT%H:%M'
    date_format: '%Y-%m-%d'

**Comment by linsvensson** [comment]
Du bör få en sensor för såld el...
Men du får alltså de andra sensorerna?
Prova att sät

**Comment by bmd322** [comment]
Jag hittar inte såld el i appen heller. Jag börjar undersöka i den änden.
