### ISSUE TITLE
current_day börjar på 02:00

### ISSUE THREAD

**Issue by HenkeGoransson** [linsvensson/sensor.greenely#22]
Current_day array:en börjar på "02:00" och slutar på "01:00"
![Capture](https://user-images.githubusercontent.com/59729272/164246107-d9cbe92c-7500-4c46-b791-df4e54a144ff.PNG)

**Comment by linsvensson** [comment]
Detta ska vara fixat i nyaste releasen, fungerar det för dig?

**Comment by HenkeGoransson** [comment]
Yes, funkar fint i senaste versionen 1.0.3
