### ISSUE TITLE
Pris från sensorn returnerar ören som SEK

### ISSUE THREAD

**Issue by mrfrostfire** [linsvensson/sensor.greenely#24]
Pris sensorn hämtar värdet i öre från Greenely.
Men standardenheten för en prissensor är SEK (om man inte valt annat) vilket gör att priset resulterar i 199.4 kr istället för 1.99Kr.
Sensorn borde ta värdet från Greenely och omvandla det, innan det presenteras till sensorn, så att sensorn kan användas som den är.

**Comment by linsvensson** [comment]
Jag håller med och ändrar så att priset skrivs ut i SEK med 4 decimaler.
Då får vi istället datan
`- date: '2022-06-25'
  time: '00:00'
  price: 0.3723`

**Comment by linsvensson** [comment]
Fixed in v1.0.4
