### ISSUE TITLE
API fails to get price

### ISSUE THREAD

**Issue by fn87** [linsvensson/sensor.greenely#27]
2022-06-23 11:43:08 ERROR (SyncWorker_8) [custom_components.greenely.api] Failed to get price data, 

Happens on both the accounts I have. Tried setting debug log level but it didn't give any feedback.

**Comment by fn87** [comment]
500 error from the API. The app doesn't use this endpoint anymore. 

A simple solution if anybody needs it is to use a template sensror like this:
` greenly_price_sek:
        unique_id: '4198402987928173'
        value_template: >-
          {% for i in states.sensor.greenely_prices.attributes.current_day %}
            {%if i.time.split(":")[0]|int == now().hour %}
              {{i.price|float/100}}
            {% endif%}
          {% endfor %}
        unit_of_measurement: SEk/kWh`

**Comment by linsvensson** [comment]
This issue should be fixed now. @fn87 can you try again and let me know if it's resolved?

**Comment by linsvensson** [comment]
Closed due to lack of response
