### ISSUE TITLE
Improved usage resolution?

### ISSUE THREAD

**Issue by f00dagi** [linsvensson/sensor.greenely#3]
Hi Lin, thanks for your work.

I would very much appreciate if you could make it possible to get hour level resolution of the usage data. It would be interesting to see how the usage changes during the day.

It would also be great if the returned data could be in format that was easy to plot in for example history-graph. Look for example at a temperature sensor that has one value and the rest in history. Easily plotted.

Thanks!

![image](https://user-images.githubusercontent.com/56124786/94350526-631a0c80-004f-11eb-932a-15f5f8586f7e.png)
![image](https://user-images.githubusercontent.com/56124786/94350552-85ac2580-004f-11eb-9e8b-21f0c73edc02.png)

**Comment by linsvensson** [comment]
I will have a look at the data to see if this is possible!

**Comment by f00dagi** [comment]
Thanks, I look forward to your update, let me know if you want me to test a new version or if you need additonal input from me. This integration has lots of potential! Thanks!

**Comment by linsvensson** [comment]
Sorry it took so long! I've had a look, and it doesn't seem like I can get the data for the current day :(

**Comment by f00dagi** [comment]
Hi Caroline, thanks for your efforts. I am not really asking for current day data, I don’t think Greenely has that data. I am more asking for hour level resolution and a way to plot the data as a graph.

See my original post. Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by linsvensson** [comment]
Sorry for the misunderstanding.
I might be able to get the hourly data, I'll have a look now.
As for plotting the data as a graph I have looked into that before without any success sadly.

**Comment by linsvensson** [comment]
Okay, I'm testing some additions to the code now.
I'm making the state  value yesterday's total usage so you should be able to make a graph with that.
Then the hourly attribute shows yesterday's hourly usage.
Will something like this work?
![Capture](https://user-images.githubusercontent.com/5594088/100553119-302d0880-328c-11eb-931a-346186cfb6e1.PNG)

**Comment by f00dagi** [comment]
Cool, thanks, I was about to try it but it seems like you have not posted your update for me to download? Please do so and I am happy to test your updates.

**Comment by linsvensson** [comment]
Pushed now!

**Comment by f00dagi** [comment]
Thanks!

I added your new version but the graph remains flat, depending on your implementation maybe I need to wait a couple of days for the graph to show data?
![image](https://user-images.githubusercontent.com/56124786/100592311-37d5c700-32f7-11eb-8ecb-b17d474a99d1.png)

**Comment by linsvensson** [comment]
Hm I can't see yesterday's data yet in the app, I'm not sure when during the day it gets updated 🤔 But as soon as it does, it should show up in home assistant!

**Comment by f00dagi** [comment]
Awesome! Can now ser data for yesterday (orange bar graph). If you want to continue development I would like to refer back to the original post of hourly resolution.

In the Greenely app you can ser data per day (as tou have done now), but also per hour. That woulf be a nice option to have (green bar graphs).

![C69E608B-7F3F-4703-B731-28A28F990380](https://user-images.githubusercontent.com/56124786/100602398-234bfb80-3304-11eb-9e90-2f601d539b18.png)
![627955CC-72D2-4756-8B46-6E3F0AACEF94](https://user-images.githubusercontent.com/56124786/100602404-247d2880-3304-11eb-84b4-d36ddd178332.png)
![471F53E2-59EF-40A8-A57D-CBE3CA7B36E8](https://user-images.githubusercontent.com/56124786/100602407-247d2880-3304-11eb-8736-63533a89d9a8.png)

**Comment by linsvensson** [comment]
Great! I'm glad it worked out.
Have you added `show_hourly: true`? 
Or is that data not what you had in mind?

**Comment by f00dagi** [comment]
Yes, but I did that after the data was transferred to HA, maybe I need to wait for the next data transfer tomorrow to get hourly resolution in HA then?

**Comment by linsvensson** [comment]
Do you have any hourly data yet?

**Comment by f00dagi** [comment]
Thanks for following up on this. I get the hourly data now, as can be seen in the attached image.
But when plotting:
- hourly data is not plotted
- daily data goes down to zero between two adjacent days (but there is no zero data point in the 'Days' data)

Hard for me to speculate about the root cause but might have to do with how a data points (x:time and y:usage) is assembled for the graph to use?

I only have three data points so far but it looks a bit strange. If you want to continue working on it I am happy to try new commits.

![image](https://user-images.githubusercontent.com/56124786/100759651-2670e580-33f1-11eb-8b56-a508c39c9c63.png)

**Comment by linsvensson** [comment]
As far as I know the graph will only show the state value, but maybe I can improve that somehow.
The sensor does a check every hour. It SHOULD then set the state value to yesterday's combined usage. That doesn't seem to be the case in the screenshot you sent, so I'll have a look at the code.

Right now the only good way to visualize the hourly data that I can see is using the flex-table-card.

**Comment by f00dagi** [comment]
I would propose two sensors
- sensor.greenely_hourly
- sensor.greenely_daily

See my attached sketch.

For inspiration look at a (simple) temperature sensor that gets data every 30 minutes and is easily plotted in HA. It it definitely possible.

![aaa](https://user-images.githubusercontent.com/56124786/100787448-f1c25580-3413-11eb-9c19-54b194500d19.jpg)
![image](https://user-images.githubusercontent.com/56124786/100787665-4796fd80-3414-11eb-8c79-27675a4ba1eb.png)

I appreciate your perseverance :)

**Comment by f00dagi** [comment]
For your reference, another day of data.

![4FA79097-FB70-460B-BED9-47B0759B39EF](https://user-images.githubusercontent.com/56124786/100918733-2b10c900-34d9-11eb-93ba-cf233930f91a.jpeg)

**Comment by AndersHub** [comment]
Hi, I'm struggling to get some nice curves out of Greenely which should not be impossible. The data is there so it's about my shortcoming.

I have tried to work with Card config: 'custom: mini-graph-card' 'and added the following:
hours_to_show: 480
group_by: date
show:
   graph: bar

I got some result but not relevant :(

Someone who has any tips for getting ahead or maybe another Card?

**Comment by tempmaseg** [comment]
Use this one to create a graph: https://github.com/RomRider/apexcharts-card
![apexcarts](https://user-images.githubusercontent.com/55505550/145798605-c6add66f-d047-4576-9fcf-17e09c133663.png)

**Comment by linsvensson** [comment]
@tempmaseg Oh nice! I'll test that and add it to the README

**Comment by tempmaseg** [comment]
@linsvensson - My lovelace code :) (You can probably just swap nordpool to greenely for the price. However, I use the nordpool in another graph to display todays price and tomorrows. Hence, not using the greenely price)

type: custom:apexcharts-card
header:
  title: Förbrukning/timme & elpriset
  show: true
graph_span: 25h
span:
  start: day
  offset: '-1d'
yaxis:
  - id: first
    apex_config:
      tickAmount: 10
    min: 0
    max: 2
  - id: second
    opposite: true
    apex_config:
      tickAmount: 5
    min: 0
    decimals: 0
apex_config:
  dataLabels:
    enabled: false
  stroke:
    width: 4
series:
  - entity: sensor.greenely_usage
    name: Förbrukning
    yaxis_id: first
    type: column
    color: red
    extend_to_end: false
    show:
      legend_value: false
    data_generator: |
      return entity.attributes.hourly.map((entry) => {
        return [new Date(entry.time), entry.usage];
      }); 
  - entity: sensor.nordpool_kwh_se3_sek_1_10_025
    yaxis_id: second
    type: line
    color: blue
    name: Elpriset
    show:
      legend_value: false
    extend_to_end: false

**Comment by linsvensson** [comment]
@tempmaseg Awesome thanks!

**Comment by tempmaseg** [comment]
Sure, np :)

Glad I could help out!

**Comment by linsvensson** [comment]
@tempmaseg I just realised that you use -1d offset, does the nordpool sensor show yesterdays price?

**Comment by tempmaseg** [comment]
I am using two types of data to populate the graph:

The first one is the greenely sensor, and by using the data_generator the data is fetched from the sensors attributes. 
,,,
  series:
    - entity: sensor.greenely_usage
      name: Förbrukning
      yaxis_id: first
      type: column
      color: red
      extend_to_end: false
      show:
        legend_value: false
      data_generator: |
        return entity.attributes.hourly.map((entry) => {
          return [new Date(entry.time), entry.usage];
        }); 
,,,

For the prices, I am not using the data generator and instead the state of the sensor is used. The state of the sensor is automatically saved as history in HA hence it is possible to get the values for yesterday :)

I havent tested it for the greenely sensor for prices but it works with nordpools 
,,,
    - entity: sensor.greenely_prices
      yaxis_id: second
      type: line
      color: blue
      name: Elpris
      show:
        legend_value: false
      extend_to_end: false
,,,

**Comment by linsvensson** [comment]
Makes sense! I added an attribute for previous day to prices so it should be fine :)

**Comment by tempmaseg** [comment]
Nice! =)

**Comment by AndersHub** [comment]
Hi I also use Apex but I have some problem regadring Greenly and your code. I get this error "/// apexcharts-card version 1.10.0 /// value.header is not a ChartCardHeaderExternalConfig; value.header.graph_span is extraneous" . 

Have you or someone else any idea and hopefully some solution?
