### ISSUE TITLE
More data?

### ISSUE THREAD

**Issue by logicalshrapnel** [linsvensson/sensor.greenely#38]
Hey. I've been working on a node-red version of this and got it working. Have yet to put it online however. 
Your code was a great start. Thanks!

I'm curious how you found out the methods to call as the app now has a bit more features and I'd assume that data would be available too if one knew where to look. Any suggestions on how to find the URLs?

**Comment by fldc** [comment]
Analyze the traffic with something like Wireshark while using the app?

**Comment by linsvensson** [comment]
I used logcat in Android Studio to see the requests, you could try that?

**Comment by logicalshrapnel** [comment]
Thanks, I'll try that. 

(And @fldc that won't work with https traffic.)
