### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by pomah86** [linsvensson/sensor.greenely#4]
Greenely just updated their app with electricity produced and sold, is it possible to also add the sold feature into the custom sensor?

BR Roman M

**Comment by linsvensson** [comment]
I'm not able to see this in my app... If I can somehow find out what api call is being made then I can have a look.

**Comment by pomah86** [comment]
I have added some images on how it looks on my phone, if I can help getting the API call somehow I will help, I just don't know how to do it. 

![image](https://user-images.githubusercontent.com/7014789/100619333-48009d00-331d-11eb-9b11-f101e5a2a2bf.png)

![image](https://user-images.githubusercontent.com/7014789/100619783-e987ee80-331d-11eb-8ea9-da25ae00f3a6.png)

![image](https://user-images.githubusercontent.com/7014789/100619810-f1479300-331d-11eb-890d-e42021788f3f.png)

**Comment by linsvensson** [comment]
I use the log in Android Studio to track down the API calls, but I'll see if I can find a better way!

**Comment by linsvensson** [comment]
I can't seem to find another option :( 
What you can do is download Android Studio, plug in your phone to the PC and start the Greenely app, then open logcat and search for "greenely". When you navigate to the History tab in the app the log will print out any api calls it makes. 
I've taken a screenshot of what it will look like. 
Let me know if you need help!
![Capture](https://user-images.githubusercontent.com/5594088/100651921-83639180-3346-11eb-99a0-aaea7c53f682.PNG)

**Comment by mekluuba** [comment]
Hi, as i didnt have github and my friend pomah86 had, i asked him to issue this request. 
Also screenshots are from my login. I tried to get android studio to work. But i cant find the logcat window in my version.. 

Maybe easiest would be for you to test my login for greenely to see if you can find what you need? 

Best regards, 
Victor

**Comment by linsvensson** [comment]
If you feel comfortable with me logging in to your account I can definitely do that :)
You can email me at carolin.svensson@live.se

**Comment by AndersHub** [comment]
Any results regarding getting pictures above into HA?

**Comment by tempmaseg** [comment]
Have a look at: #3, it should help you out.

**Comment by linsvensson** [comment]
> Any results regarding getting pictures above into HA?

I haven't had a chance to look at that, but it feels like that would be done with a card.
