### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by AndersHub** [linsvensson/sensor.greenely#5]
Hi Lin, Great work you have done. I am new in this exciting area and probably a bit stupid. I have read your installation guide but it dosent work for me.

I download three files from your custom_components/greenely/ into my custom_components/greenely/. I set up the sensor code in my /config/configuration.yaml as you say but it doesn't work.

You also say this:
_"Using your HA configuration directory (folder) as a starting point you should now also have this:

custom_components/greenely/__init__.py
custom_components/greenely/sensor.py
custom_components/greenely/manifest.json"_

Shall I put these three rows into my /config/configuration.yaml or what don't I understand or do wrong?

Thanks in advance.
Anders

**Comment by linsvensson** [comment]
Hi Anders,
Thanks! It's okay, it takes a while to get into!

Are you able to check your Home Assistant log to see if it mentions greenely? 
You can find it under Configuration -> Logs

This part:
`_"Using your HA configuration directory (folder) as a starting point you should now also have this:`
is just referring to what the folder should look like :)

**Comment by AndersHub** [comment]
The log is empty and I can not find any Greenely sensors in my long list of other sensors in my Entitet list.

**Comment by AndersHub** [comment]
Don't ask me why but now it works :)

**Comment by henkethebenke** [comment]
After I restarted my RPi the Greenely sensor showed up.
