### ISSUE TITLE
Inga värden

### ISSUE THREAD

**Issue by danielbergholm** [linsvensson/sensor.greenely#52]
Jag har ett problem. Jag får inte in några värden under Greenely. Den visar bara noll på både daglig förbrukning och timförbrukning. Har installerat via HACS och inte lagt till något särskilt (mer än användarnamn, lösenord och att den ska visa just timförbrukning) i konfigurationen. Varför blir det såhär?

![Screenshot 2024-03-31 21 46 42](https://github.com/linsvensson/sensor.greenely/assets/158089631/7dae0962-c78c-4a17-b42f-90c87a4a8ae6)

Trycker jag på kugghjulet visar den följande:
![Screenshot 2024-03-31 21 49 12](https://github.com/linsvensson/sensor.greenely/assets/158089631/a5d07954-9a69-4032-a069-911763a62b11)

**Comment by henrikbla** [comment]
Kan bekräfta att mitt installation har samma problem.

**Comment by danielbergholm** [comment]
> Kan bekräfta att mitt installation har samma problem.

Intressant! Är du kund hos Greenely? Jag är inte det och tänker att det kanske kan bero på det? Men man tycker ju att värdena borde komma över ändå?

**Comment by henrikbla** [comment]
> > Kan bekräfta att mitt installation har samma problem.
> 
> 
> 
> Intressant! Är du kund hos Greenely? Jag är inte det och tänker att det kanske kan bero på det? Men man tycker ju att värdena borde komma över ändå?

Nej, är inte kund hos Greenely. Jag tror inte det spelar någon roll faktiskt, för värdena visas rätt i Greenely's eget app fortfarande. Det är bara HA-appen som verkar ha problem.

**Comment by danielbergholm** [comment]
> > > Kan bekräfta att mitt installation har samma problem.
> > 
> > 
> > Intressant! Är du kund hos Greenely? Jag är inte det och tänker att det kanske kan bero på det? Men man tycker ju att värdena borde komma över ändå?
> 
> Nej, är inte kund hos Greenely. Jag tror inte det spelar någon roll faktiskt, för värdena visas rätt i Greenely's eget app fortfarande. Det är bara HA-appen som verkar ha problem.

Samma här! Hoppas det kan lösa sig, någon gång!

**Comment by niXta1** [comment]
Det verkar som att det är något som har ändrats, finns det någon möjlighet att ta en titt på det @linsvensson ? 🙏🏼

**Comment by danielbergholm** [comment]
Vore också givetvis tacksam för detta @linsvensson !

**Comment by linsvensson** [comment]
Hm, allt annat fungerar? Ni kan se data i appen?
Testa gärna [detta ](https://github.com/linsvensson/sensor.greenely?tab=readme-ov-file#debug-logging) och se vad som skrivs ut i loggen.

**Comment by danielbergholm** [comment]
Japp, alla data stämmer i appen. Jag får fyra felloggar som ser ut såhär efter att ha lagt till det du skrev:

Felet härrör från en anpassad integration.

1.
Logger: custom_components.greenely.api
Källa: custom_components/greenely/api.py:77
integration: greenely (dokumentation, ärenden)
Inträffade först: 20:50:51 (1 händelser)
Senast loggade: 20:50:51

Failed to fetch facility id {"title":"404 Not Found","jwt":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJleHAiOjE3MjMzMTU4NTEuMCwiYXV0aCI6eyJ1c2VyX2lkIjozMDA2NDF9fQ.tNNgXXFtj_WsghoVn2CWoZQAh0CVgMwLbmw8a7Uwd5IVtusd5FUsemjOXKR82acWOeKTy4IfXQxYSrfRUB_EwA"}

2.
Felet härrör från en anpassad integration.

Logger: custom_components.greenely.api
Källa: custom_components/greenely/api.py:67
integration: greenely (dokumentation, ärenden)
Inträffade först: 20:50:51 (1 händelser)
Senast loggade: 20:50:51

Failed to fetch usage data, {"title":"404 Not Found","jwt":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJleHAiOjE3MjMzMTU4NTEuMCwiYXV0aCI6eyJ1c2VyX2lkIjozMDA2NDF9fQ.tNNgXXFtj_WsghoVn2CWoZQAh0CVgMwLbmw8a7Uwd5IVtusd5FUsemjOXKR82acWOeKTy4IfXQxYSrfRUB_EwA"}

3.
Felet härrör från en anpassad integration.

Logger: custom_components.greenely.api
Källa: custom_components/greenely/api.py:37
integration: greenely (dokumentation, ärenden)
Inträffade först: 20:50:52 (1 händelser)
Senast loggade: 20:50:52

Failed to get price data, {"title":"404 Not Found","jwt":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJleHAiOjE3MjMzMTU4NTEuMCwiYXV0aCI6eyJ1c2VyX2lkIjozMDA2NDF9fQ.tNNgXXFtj_WsghoVn2CWoZQAh0CVgMwLbmw8a7Uwd5IVtusd5FUsemjOXKR82acWOeKTy4IfXQxYSrfRUB_EwA"}

4.
Felet härrör från en anpassad integration.

Logger: custom_components.greenely.api
Källa: custom_components/greenely/api.py:53
integration: greenely (dokumentation, ärenden)
Inträffade först: 20:50:52 (1 händelser)
Senast loggade: 20:50:52

Failed to get spot price data, {"title":"404 Not Found","jwt":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJleHAiOjE3MjMzMTU4NTEuMCwiYXV0aCI6eyJ1c2VyX2lkIjozMDA2NDF9fQ.tNNgXXFtj_WsghoVn2CWoZQAh0CVgMwLbmw8a7Uwd5IVtusd5FUsemjOXKR82acWOeKTy4IfXQxYSrfRUB_EwA"}

Tacksam för hjälp!

**Comment by henrikbla** [comment]
Jag (den andra påverkade person på den här tråden) har tyvärr inte möjlighet att gräva fram felloggar just nu, har stambyte i våran lägenhet och Home Assistant är nere för en månad till.

**Comment by linsvensson** [comment]
@danielbergholm Aha, ser vad problemet är. De anropen sensorn gör antar att du har en primary facility satt, men det verkar du inte ha. Ska se om jag kan sätta upp det på ett bättre sätt!

**Comment by danielbergholm** [comment]
Spännande, se vad som kan göras! Tack! 😀

**Comment by linsvensson** [comment]
Kolla gärna om den nya uppdateringen fixade problemet!

**Comment by danielbergholm** [comment]
Absolut att den gjorde! Nu verkar det lira! Stort tack @linsvensson! Kudos!
