### ISSUE TITLE
I don't understand what UI are you referring to

### ISSUE THREAD

**Issue by TSA3000** [linsvensson/sensor.greenely#57]
![image](https://github.com/user-attachments/assets/02434af8-3b30-4dbf-bd3a-1c6af8dc7612)
What do you mean with UI what UI?
Could please explain what should I do after the last update?

**Comment by TSA3000** [comment]
Hej Kan du vara snäll och förklara vad var du menade med UI, i vilken vy?

**Comment by henrikbla** [comment]
UI:n i Home Assistant, alltså tryck på Settings - Intrgrations - Add Integration och sök efter Greenely.

Glöm inte att ta bort YAML-koden från configuration.yaml också.

**Comment by Gummiberra** [comment]
Precis som @henrikbla skriver så kan man nu lägga till integrationen via integrations tabben under settings. Kanske skrev lite för slarvig readme. Kan lägga till en mer utförlig formulering i readme i nästa version, jobbar på att få in såld el i integrationen. Just nu verkar de vara ganska mycket störningar i appen så får inte ut några api calls.

**Comment by enoch85** [comment]
http://1.2.3.4/config/integrations/integration/greenely

![image](https://github.com/user-attachments/assets/94940288-f1a4-4271-a57b-0e9a1bca602f)

![image](https://github.com/user-attachments/assets/ce9af2c6-eae6-4f75-a7a5-9b5dc3ad3ef1)
