### ISSUE TITLE
Platform error sensor.greenely - Integration 'greenely' not found.

### ISSUE THREAD

**Issue by tommytoad** [linsvensson/sensor.greenely#7]
Did this component stop working with newer Hass versions or something?

Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:486
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 21:15:19 (1 occurrences)
Last logged: 21:15:19

Platform error sensor.greenely - Integration 'greenely' not found.

Files in place:
\config\custom_components\greenely\_init_.py
\config\custom_components\greenely\manifest.json
\config\custom_components\greenely\sensor.py
All with the correct permissions.

Supervisor
Version
supervisor-2021.04.0

Operativsystem
Home Assistant OS 5.13

Home Assistant 2021.4.6

**Comment by linsvensson** [comment]
Hmm it should be working still. 
Could you try adding this to your logger and see if it prints out anything?
`custom_components.greenely: debug`

**Comment by tommytoad** [comment]
Nothing helpful unfortunately:

`2021-04-23 13:35:06 ERROR (MainThread) [homeassistant.components.hassio] Platform error sensor.greenely - Integration 'greenely' not found.
2021-04-23 13:37:13 ERROR (MainThread) [homeassistant.components.hassio] Platform error sensor.greenely - Integration 'greenely' not found.`

**Comment by matteskonto** [comment]
I just installed it and it was working for me on 2021.08 and HA OS 6.2.

Make sure that all three files are present in the folder, I don't know if it is a typo but the first file seems wrong:
 
> Files in place:
> \config\custom_components\greenely_init_.py
> \config\custom_components\greenely\manifest.json
> \config\custom_components\greenely\sensor.py
> All with the correct permissions.
>
