### ISSUE TITLE
Error on device update

### ISSUE THREAD

**Issue by johanfolin** [linsvensson/sensor.greenely#8]
Hi, I get this error when trying to load the Greenely sensor. Taken from the Core log:

`2021-08-06 11:04:08 ERROR (MainThread) [homeassistant.components.sensor] greenely: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 646, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/greenely/sensor.py", line 319, in update
    response = self._api.get_sold(self._sold_measure, self._sold_daily)
  File "/config/custom_components/greenely/sensor.py", line 417, in get_sold
    _LOGGER.error('Failed to fetch sold data from %s, %s', first_month.strftime("%d/%m/%Y"), response.text)
UnboundLocalError: local variable 'first_month' referenced before assignment`

I'm a newbie in using Home Assistant, so it is quite possible that I have done something wrong. I put the example code (with my own e-mail and password) for the integration in configuration.yaml.

**Comment by johanfolin** [comment]
The error might be due to the fact that I haven't sold any electricity to Greenely yet. I am currently switching to Greenely as buyer for my generated solar electricity, but the change hasn't taken effect yet.

**Comment by linsvensson** [comment]
Does it work if you disable sold?
`sold: false`

**Comment by johanfolin** [comment]
Yes it does. I haven't had any luck with the customized cards yet, but the entities are there and are reporting (I think) correct data.

**Comment by linsvensson** [comment]
That's good then. As soon as the Greenely app starts showing stats for sold, you can add it again.
